# baseUrl: file:///e:/0-教学课件/class2023_CUG_HydroMet/index.md
# baseUrl: https://github.com/CUG-hydro/class2023_CUG_HydroMet/blob/master/index.md
# baseUrl: https://raw.githubusercontent.com/CUG-hydro/class2023_CUG_HydroMet/master/images/
